# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.4.0/opencode-mac-x86_64.tar.gz"
      sha256 "570ae07595fde22a22a0cee7de22cdd4862722cac471f0910bc01ddc969caa7c"

      define_method(:install) do
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.4.0/opencode-mac-arm64.tar.gz"
      sha256 "17942063180ed74efa2d9228d355da3eb3aa82e723323ef60aa6150dc9e403e2"

      define_method(:install) do
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.4.0/opencode-linux-x86_64.tar.gz"
      sha256 "192c351871a450b5c8e27d7d64fbbeb0239e0d9b464d035131a0bb871737ff68"
      define_method(:install) do
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.4.0/opencode-linux-arm64.tar.gz"
      sha256 "593ec1efb5542f68196576c010fa4b5150d374d5875550f0bacdc098f4d395e1"
      define_method(:install) do
        bin.install "opencode"
      end
    end
  end
end
