# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opencode < Formula
  desc ""
  homepage ""
  version "0.13.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.13.6/opencode-mac-x86_64.tar.gz"
      sha256 "fc4e325146f7873a68d13bcba49c7336332205f4a571beb1c827f5c97f185562"

      define_method(:install) do
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.13.6/opencode-mac-arm64.tar.gz"
      sha256 "d0cd6898db74ec7efaa50266db57ef380bb98cde180c0f94f66af5a40da3b239"

      define_method(:install) do
        bin.install "opencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.13.6/opencode-linux-x86_64.tar.gz"
      sha256 "3141c5b2ba427bf21290db57466a5058ae42a8592efc52ff55db266ae05ef99e"
      define_method(:install) do
        bin.install "opencode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obukhovaa/opencode/releases/download/v0.13.6/opencode-linux-arm64.tar.gz"
      sha256 "ad44d362d4c7b92c8b39d308430eb8754d3df85eb13965c1c943dd44ccbf2b00"
      define_method(:install) do
        bin.install "opencode"
      end
    end
  end
end
